<?php
namespace App\Http\Controllers\Payment;

use Symfony\Component\HttpFoundation\Response;
use Laravel\Cashier\Http\Controllers\WebhookController as CashierController;

class StripeWebhookController extends CashierController
{
    protected function successMethod($parameters = [])
    {
        return parent::successMethod($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * Handle invoice payment succeeded.
     *
     * @param  array  $payload
     * @return Response
     */
    public function handleWebhook($payload = null)
    {
        // Handle the incoming event...
        return view('public.payment.webhook', compact('payload'));
    }

    public function handleAsyncPaymentSucceeded($payload = null)
    {
        // Handle the incoming event...
        dd($payload);
    }

    public function handleAsyncPaymentFailed($payload = null)
    {
        // Handle the incoming event...
        dd($payload);
    }

    public function handleCompleted($payload = null)
    {
        // Handle the incoming event...
        dd($payload);
    }

    public function handleAll($payload = null)
    {
        // Handle the incoming event...
        dd($payload);
    }
}
